
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class Departmanlar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Departmanlar()
    {

        this.UrunKategoriler = new HashSet<UrunKategoriler>();

    }


    public int departmanId { get; set; }

    public string departmanAd { get; set; }

    public string departmanIp { get; set; }

    public bool aktifMi { get; set; }

    public int subeId { get; set; }

    public bool silindi { get; set; }



    public virtual Subeler Subeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UrunKategoriler> UrunKategoriler { get; set; }

}

}
