
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class FaturadakiHizmetler
{

    public int faturadakiHizmetId { get; set; }

    public int hizmetId { get; set; }

    public int faturaId { get; set; }

    public int paraBirimiId { get; set; }

    public int adet { get; set; }

    public bool yillikMi { get; set; }

    public Nullable<int> hizmetKampanyaId { get; set; }

    public bool silindi { get; set; }



    public virtual Faturalar Faturalar { get; set; }

    public virtual Hizmetler Hizmetler { get; set; }

    public virtual ParaBirimleri ParaBirimleri { get; set; }

}

}
