
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class ParaBirimleri
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ParaBirimleri()
    {

        this.FaturadakiHizmetler = new HashSet<FaturadakiHizmetler>();

        this.FaturaOdemeleri = new HashSet<FaturaOdemeleri>();

        this.HizmetKampanyalari = new HashSet<HizmetKampanyalari>();

        this.Hizmetler = new HashSet<Hizmetler>();

        this.Menuler = new HashSet<Menuler>();

        this.OdemeTurleri = new HashSet<OdemeTurleri>();

    }


    public int paraBirimiId { get; set; }

    public string paraBirimiAd { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FaturadakiHizmetler> FaturadakiHizmetler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FaturaOdemeleri> FaturaOdemeleri { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HizmetKampanyalari> HizmetKampanyalari { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Hizmetler> Hizmetler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Menuler> Menuler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OdemeTurleri> OdemeTurleri { get; set; }

}

}
