
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class Personeller
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Personeller()
    {

        this.Siparisler = new HashSet<Siparisler>();

    }


    public int personelId { get; set; }

    public string personelAd { get; set; }

    public string personelParola { get; set; }

    public string personelEmail { get; set; }

    public string personelTelefon { get; set; }

    public bool yetki { get; set; }

    public int subeId { get; set; }

    public bool silindi { get; set; }

    public bool masaModuMu { get; set; }



    public virtual Subeler Subeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Siparisler> Siparisler { get; set; }

}

}
