
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class Siparisler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Siparisler()
    {

        this.SiparisUrunleri = new HashSet<SiparisUrunleri>();

        this.YazdirmaListesi = new HashSet<YazdirmaListesi>();

    }


    public int siparislerId { get; set; }

    public System.DateTime siparisTarihi { get; set; }

    public bool siparisDurumu { get; set; }

    public string note { get; set; }

    public int oturumId { get; set; }

    public int personelId { get; set; }

    public int subeId { get; set; }

    public bool silindi { get; set; }



    public virtual Oturumlar Oturumlar { get; set; }

    public virtual Personeller Personeller { get; set; }

    public virtual Subeler Subeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SiparisUrunleri> SiparisUrunleri { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<YazdirmaListesi> YazdirmaListesi { get; set; }

}

}
