
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class SiparisUrunleri
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SiparisUrunleri()
    {

        this.SiparisUrunleriEkstralari = new HashSet<SiparisUrunleriEkstralari>();

    }


    public int siparisUrunlerId { get; set; }

    public int siparislerId { get; set; }

    public int urunId { get; set; }

    public bool onaylandi { get; set; }

    public bool odendi { get; set; }

    public int urunOzellikId { get; set; }

    public Nullable<int> oturumKampanyaId { get; set; }

    public Nullable<System.DateTime> odenmeTarihi { get; set; }

    public bool silindi { get; set; }



    public virtual OturumKampanyalari OturumKampanyalari { get; set; }

    public virtual Siparisler Siparisler { get; set; }

    public virtual Urunler Urunler { get; set; }

    public virtual UrunOzellikler UrunOzellikler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SiparisUrunleriEkstralari> SiparisUrunleriEkstralari { get; set; }

}

}
