
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class Sirketler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sirketler()
    {

        this.Faturalar = new HashSet<Faturalar>();

        this.Subeler = new HashSet<Subeler>();

    }


    public int sirketId { get; set; }

    public string sirketAd { get; set; }

    public string sirketEmail { get; set; }

    public string sirketTelefon { get; set; }

    public string sirketParola { get; set; }

    public int ilceId { get; set; }

    public bool aktiflestirildiMi { get; set; }

    public string aktiflestirmeKodu { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Faturalar> Faturalar { get; set; }

    public virtual Ilceler Ilceler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Subeler> Subeler { get; set; }

}

}
