
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class Subeler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Subeler()
    {

        this.Departmanlar = new HashSet<Departmanlar>();

        this.Duyurular = new HashSet<Duyurular>();

        this.HizmetLisanslari = new HashSet<HizmetLisanslari>();

        this.Kampanyalar = new HashSet<Kampanyalar>();

        this.Katlar = new HashSet<Katlar>();

        this.Menuler = new HashSet<Menuler>();

        this.Odemeler = new HashSet<Odemeler>();

        this.OdemeTurleri = new HashSet<OdemeTurleri>();

        this.Oturumlar = new HashSet<Oturumlar>();

        this.Personeller = new HashSet<Personeller>();

        this.Siparisler = new HashSet<Siparisler>();

        this.Urunler = new HashSet<Urunler>();

        this.UrunStoklar = new HashSet<UrunStoklar>();

        this.YazdirmaListesi = new HashSet<YazdirmaListesi>();

    }


    public int subeId { get; set; }

    public string subeAd { get; set; }

    public string subeAdres { get; set; }

    public bool ilkKurulumYapildiMi { get; set; }

    public int sirketId { get; set; }

    public int ilceId { get; set; }

    public bool duyuruAlaniAktifMi { get; set; }

    public bool personelYazicisiOtomatikMi { get; set; }

    public string kasaYaziciIp { get; set; }

    public string personelYaziciIp { get; set; }

    public string kasaYaziciAd { get; set; }

    public string personelYaziciAd { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Departmanlar> Departmanlar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Duyurular> Duyurular { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HizmetLisanslari> HizmetLisanslari { get; set; }

    public virtual Ilceler Ilceler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kampanyalar> Kampanyalar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Katlar> Katlar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Menuler> Menuler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Odemeler> Odemeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OdemeTurleri> OdemeTurleri { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Oturumlar> Oturumlar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Personeller> Personeller { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Siparisler> Siparisler { get; set; }

    public virtual Sirketler Sirketler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Urunler> Urunler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UrunStoklar> UrunStoklar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<YazdirmaListesi> YazdirmaListesi { get; set; }

}

}
