
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurantPosPrinterSoftware
{

using System;
    using System.Collections.Generic;
    
public partial class UrunKategoriler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UrunKategoriler()
    {

        this.Urunler = new HashSet<Urunler>();

    }


    public int urunKategoriId { get; set; }

    public string urunKategoriAd { get; set; }

    public int departmanId { get; set; }

    public int menuId { get; set; }

    public double vergiYuzde { get; set; }

    public bool silindi { get; set; }



    public virtual Departmanlar Departmanlar { get; set; }

    public virtual Menuler Menuler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Urunler> Urunler { get; set; }

}

}
