
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class Duyurular
{

    public int duyuruId { get; set; }

    public string duyuruBaslik { get; set; }

    public string duyuruAciklama { get; set; }

    public string duyuruResim { get; set; }

    public bool yayinda { get; set; }

    public int subeId { get; set; }

    public bool silindi { get; set; }



    public virtual Subeler Subeler { get; set; }

}

}
