
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class Faturalar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Faturalar()
    {

        this.FaturadakiHizmetler = new HashSet<FaturadakiHizmetler>();

        this.FaturaOdemeleri = new HashSet<FaturaOdemeleri>();

        this.HizmetLisanslari = new HashSet<HizmetLisanslari>();

    }


    public int faturaId { get; set; }

    public System.DateTime faturaTarih { get; set; }

    public bool odendiMi { get; set; }

    public int sirketId { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FaturadakiHizmetler> FaturadakiHizmetler { get; set; }

    public virtual Sirketler Sirketler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FaturaOdemeleri> FaturaOdemeleri { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HizmetLisanslari> HizmetLisanslari { get; set; }

}

}
