
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class HizmetKampanyaHizmetleri
{

    public int hizmetKampanyaHizmetId { get; set; }

    public int hizmetId { get; set; }

    public int hizmetKampanyaId { get; set; }

    public bool silindi { get; set; }



    public virtual HizmetKampanyalari HizmetKampanyalari { get; set; }

    public virtual Hizmetler Hizmetler { get; set; }

}

}
