
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class Hizmetler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hizmetler()
    {

        this.FaturadakiHizmetler = new HashSet<FaturadakiHizmetler>();

        this.HizmetKampanyaHizmetleri = new HashSet<HizmetKampanyaHizmetleri>();

        this.HizmetLisanslari = new HashSet<HizmetLisanslari>();

    }


    public int hizmetId { get; set; }

    public string hizmetAd { get; set; }

    public double hizmetAylikUcret { get; set; }

    public int paraBirimiId { get; set; }

    public short hizmetTuru { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FaturadakiHizmetler> FaturadakiHizmetler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HizmetKampanyaHizmetleri> HizmetKampanyaHizmetleri { get; set; }

    public virtual ParaBirimleri ParaBirimleri { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HizmetLisanslari> HizmetLisanslari { get; set; }

}

}
