
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class HizmetKampanyalari
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HizmetKampanyalari()
    {

        this.HizmetKampanyaHizmetleri = new HashSet<HizmetKampanyaHizmetleri>();

    }


    public int hizmetKampanyaId { get; set; }

    public string hizmetKampanyaAd { get; set; }

    public double hizmetKampanyaFiyat { get; set; }

    public int paraBirimiId { get; set; }

    public bool yillikMi { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HizmetKampanyaHizmetleri> HizmetKampanyaHizmetleri { get; set; }

    public virtual ParaBirimleri ParaBirimleri { get; set; }

}

}
