

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class iRestaurantDataBaseClass : DbContext
{
    public iRestaurantDataBaseClass()
        : base("name=iRestaurantDataBaseClass")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Departmanlar> Departmanlar { get; set; }

    public virtual DbSet<Duyurular> Duyurular { get; set; }

    public virtual DbSet<FaturadakiHizmetler> FaturadakiHizmetler { get; set; }

    public virtual DbSet<Faturalar> Faturalar { get; set; }

    public virtual DbSet<FaturaOdemeleri> FaturaOdemeleri { get; set; }

    public virtual DbSet<HizmetKampanyaHizmetleri> HizmetKampanyaHizmetleri { get; set; }

    public virtual DbSet<HizmetKampanyalari> HizmetKampanyalari { get; set; }

    public virtual DbSet<Hizmetler> Hizmetler { get; set; }

    public virtual DbSet<HizmetLisanslari> HizmetLisanslari { get; set; }

    public virtual DbSet<Ilceler> Ilceler { get; set; }

    public virtual DbSet<Iller> Iller { get; set; }

    public virtual DbSet<Kampanyalar> Kampanyalar { get; set; }

    public virtual DbSet<KampanyaUrunleri> KampanyaUrunleri { get; set; }

    public virtual DbSet<Katlar> Katlar { get; set; }

    public virtual DbSet<Masalar> Masalar { get; set; }

    public virtual DbSet<Menuler> Menuler { get; set; }

    public virtual DbSet<Odemeler> Odemeler { get; set; }

    public virtual DbSet<OdemeTurleri> OdemeTurleri { get; set; }

    public virtual DbSet<OturumKampanyalari> OturumKampanyalari { get; set; }

    public virtual DbSet<Oturumlar> Oturumlar { get; set; }

    public virtual DbSet<ParaBirimleri> ParaBirimleri { get; set; }

    public virtual DbSet<Personeller> Personeller { get; set; }

    public virtual DbSet<Siparisler> Siparisler { get; set; }

    public virtual DbSet<SiparisUrunleri> SiparisUrunleri { get; set; }

    public virtual DbSet<SiparisUrunleriEkstralari> SiparisUrunleriEkstralari { get; set; }

    public virtual DbSet<Sirketler> Sirketler { get; set; }

    public virtual DbSet<Subeler> Subeler { get; set; }

    public virtual DbSet<Ulkeler> Ulkeler { get; set; }

    public virtual DbSet<UrunEkstralar> UrunEkstralar { get; set; }

    public virtual DbSet<UrunKategoriler> UrunKategoriler { get; set; }

    public virtual DbSet<Urunler> Urunler { get; set; }

    public virtual DbSet<UrunOzellikler> UrunOzellikler { get; set; }

    public virtual DbSet<UrunStokGirdiler> UrunStokGirdiler { get; set; }

    public virtual DbSet<UrunStoklar> UrunStoklar { get; set; }

    public virtual DbSet<YazdirmaListesi> YazdirmaListesi { get; set; }

}

}

