
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class Menuler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Menuler()
    {

        this.Kampanyalar = new HashSet<Kampanyalar>();

        this.UrunKategoriler = new HashSet<UrunKategoriler>();

    }


    public int menuId { get; set; }

    public string menuAd { get; set; }

    public int paraBirimiId { get; set; }

    public int subeId { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kampanyalar> Kampanyalar { get; set; }

    public virtual ParaBirimleri ParaBirimleri { get; set; }

    public virtual Subeler Subeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UrunKategoriler> UrunKategoriler { get; set; }

}

}
