
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class OdemeTurleri
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OdemeTurleri()
    {

        this.Odemeler = new HashSet<Odemeler>();

    }


    public int odemeTurId { get; set; }

    public string odemeTurAd { get; set; }

    public int subeId { get; set; }

    public int paraBirimiId { get; set; }

    public bool silindi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Odemeler> Odemeler { get; set; }

    public virtual ParaBirimleri ParaBirimleri { get; set; }

    public virtual Subeler Subeler { get; set; }

}

}
