
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class Oturumlar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Oturumlar()
    {

        this.Odemeler = new HashSet<Odemeler>();

        this.OturumKampanyalari = new HashSet<OturumKampanyalari>();

        this.Siparisler = new HashSet<Siparisler>();

    }


    public int oturumId { get; set; }

    public int masaId { get; set; }

    public System.DateTime oturumAcilmaTarihi { get; set; }

    public Nullable<System.DateTime> oturumKapamaTarihi { get; set; }

    public Nullable<bool> kilitlendi { get; set; }

    public Nullable<bool> odendi { get; set; }

    public bool garsonIstendi { get; set; }

    public bool hesapIstendi { get; set; }

    public int subeId { get; set; }

    public bool silindi { get; set; }



    public virtual Masalar Masalar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Odemeler> Odemeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OturumKampanyalari> OturumKampanyalari { get; set; }

    public virtual Subeler Subeler { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Siparisler> Siparisler { get; set; }

}

}
