
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class OturumKampanyalari
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OturumKampanyalari()
    {

        this.SiparisUrunleri = new HashSet<SiparisUrunleri>();

    }


    public int oturumKampanyaId { get; set; }

    public int kampanyaId { get; set; }

    public int oturumId { get; set; }

    public bool odendi { get; set; }

    public bool silindi { get; set; }



    public virtual Kampanyalar Kampanyalar { get; set; }

    public virtual Oturumlar Oturumlar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SiparisUrunleri> SiparisUrunleri { get; set; }

}

}
