
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iRestaurant
{

using System;
    using System.Collections.Generic;
    
public partial class SiparisUrunleriEkstralari
{

    public int siparisUrunEkstraId { get; set; }

    public int urunEkstraId { get; set; }

    public int siparisUrunlerId { get; set; }

    public bool odendi { get; set; }

    public bool silindi { get; set; }



    public virtual SiparisUrunleri SiparisUrunleri { get; set; }

    public virtual UrunEkstralar UrunEkstralar { get; set; }

}

}
